name: Django Test

on:
  push:
    branches: [ main, feat/*, fix/*]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Create keys.env
      uses: ozaytsev86/create-env-file@v1
      with:
        ENV_SECRET_KEY: ${{ secrets.TEST_API_KEY }}
        ENV_DB_HOST: ${{ secrets.DB_HOST }}
        ENV_DB_PORT: ${{ secrets.DB_PORT }}
        ENV_DB_NAME: ${{ secrets.DB_NAME }}
        ENV_DB_USER: ${{ secrets.DB_USER }}
        ENV_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        file-name: keys.env

    - name: Build and test Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false

    - name: Run Docker container
      env:
        DATABASE_URL: postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME
      run: |
        docker-compose --env-file=keys.env up -d
        docker-compose run --rm web python manage.py migrate
        docker-compose run --rm web python manage.py test
