name: Django Test

on:
  push:
    branches: [ main, feat/*, fix/*]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build and test Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
       
    - name: Build and test Docker image
      env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_HOST: ${{ secrets.HOST }}
          DB_PORT: ${{ secrets.PORT }}
          DB_NAME: ${{ secrets.NAME }}
          DB_USER: ${{ secrets.USER }}
          DB_PASSWORD: ${{ secrets.PASSWORD }}
      run: 
        - docker-compose build -d
        - docker-compose run web python manage.py test --verbosty 3