name: Django Test

on:
  push:
    branches: [ main, feat/*, fix/*]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Create keys.env
      uses: ozaytsev86/create-env-file@v1
      with:
        ENV_SECRET_KEY: "django-insecure-l#)$b56v$+u^sithqlgb_#l18dk(7o1_%%npk(t7!^of25z9_t"
        ENV_HOST: "db"
        ENV_PORT: 5432
        ENV_NAME: "postgres"
        ENV_USER: "postgres"
        ENV_PASSWORD: "postgres"
        file-name: keys.env

    - name: Build and test Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false

    - name: Run Docker container
      env:
        SECRET_KEY: "django-insecure-l#)$b56v$+u^sithqlgb_#l18dk(7o1_%%npk(t7!^of25z9_t"
      run: |
        docker-compose up -d
        docker-compose run --rm web python manage.py migrate
        docker-compose run --rm web python manage.py test
