name: Django Test

on:
  push:
    branches: [ main, feat/*, fix/*]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        file_name: keys.env
        fail_on_empty: false
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up environment
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: echo "SECRET_KEY=$SECRET_KEY" >> .env

    - name: Build and test Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
       
    - name: Run Docker container
      env:
        DB_HOST: ${{ secrets.HOST}}
        DB_NAME: ${{ secrets.NAME }}
        DB_USER: ${{ secrets.USER}}
        DB_PASSWORD: ${{ secrets.PASSWORD}}
      run: |
        docker-compose up -d
        docker-compose run --rm web python manage.py migrate
        docker-compose run --rm web python manage.py test
