name: Django Test

on:
  push:
    branches: [ main, feat/*, fix/*]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: ${{ secrets.NAME }}
          POSTGRES_USER: ${{ secrets.USER }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
        ports:
          5432:5432

    steps:
    - uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Create keys.env
      uses: ozaytsev86/create-env-file@v1
      with:
        ENV_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ENV_HOST: ${{ secrets.HOST }}
        ENV_PORT: ${{ secrets.PORT }}
        ENV_NAME: ${{ secrets.NAME }}
        ENV_USER: ${{ secrets.USER }}
        ENV_PASSWORD: ${{ secrets.PASSWORD }}
        file-name: keys.env

    - name: Build and test Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false

    - name: Run Docker container
      env:
        SECRET_KEY: "${{ secrets.SECRET_KEY }}"
      run: |
        docker-compose up -d
        docker-compose run --rm web python manage.py migrate
        docker-compose run --rm web python manage.py test
