name: Django Test

on:
  push:
    branches: [ main, feat/*, fix/*]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build and test Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
    
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: ${{ secrets.DEBUG }}
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_NAME: ${{ secrets.NAME }}
        envkey_USER: ${{ secrets.USER }}
        envkey_PASSWORD: ${{ secrets.PASSWORD }}
        envkey_HOST: ${{ secrets.HOST }}
        envkey_PORT: ${{ secrets.PORT }}
        file_name: keys.env
        fail_on_empty: false

    - name: Build and test Docker image
      run: |
        docker-compose build -d
        docker-compose run web python manage.py test
      env:
        # The hostname used to communicate with the PostgreSQL service container
        POSTGRES_HOST: "localhost"
        # The default PostgreSQL port
        POSTGRES_PORT: 5432

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.xml
